In [3]:
import numpy as np
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
import numpy as np
arr=np.arange(6)
arr_2d=arr.reshape(2,3)
print(arr_2d)

[[0 1 2]
 [3 4 5]]


In [6]:
my_array = np.array([[1, 2, 3], [4, 5, 6]],dtype=np.int32)
print("the shape of the array is:", my_array.shape)
print("the dimension of the array is:", my_array.ndim)
print("the size of the array is:", my_array.size)
print("the size of the each element of the array is:", my_array.itemsize)

the shape of the array is: (2, 3)
the dimension of the array is: 2
the size of the array is: 6
the size of the each element of the array is: 4


In [8]:
arr=np.ones((3,3),dtype=bool)
print(arr)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [9]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The inter

In [10]:
arr=np.linspace(5,50,10)
print(arr)    

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [12]:
my_list=[1,2,3,4,5]
arr=np.array(my_list)
print(arr)

[1 2 3 4 5]


[ 5  7 10  9]


In [ ]:
#create a array and print its memory size in bytes
arr=np.arange(10)
print("Array",arr)
print("memory size in bytes:",arr.nbytes)


Array [0 1 2 3 4 5 6 7 8 9]
memory size in bytes: 80


In [ ]:
#reate array and reverse it
arr=np.arange(10)
reversed_arr=arr[::-1]
print(reversed_arr)

[9 8 7 6 5 4 3 2 1 0]


In [ ]:
#create a array and acess the fourth element of the array and also by slicing
arr1 = np.arange(10)
print("Array 1:", arr1)
print("the fourth element of the array is:", arr1[3])
print("the fourth element by slicing is:", arr1[3:4])

Array 1: [0 1 2 3 4 5 6 7 8 9]
the fourth element of the array is: 3
the fourth element by slicing is: [3]


In [ ]:
#create identity matrix of size 3*3
idenity=np.eye(3)
print(idenity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#delete the seond row of the array

In [25]:
#create a array and etract its first row and last column
arr=np.arange(1,17).reshape(4,4)
print("Array:\n",arr)
print("First row:\n",arr[0])
print("Last column:\n",arr[:, -1])

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First row:
 [1 2 3 4]
Last column:
 [ 4  8 12 16]


In [26]:
#all numbers between 5 and 10
arr=np.array([1,5,7,10,12,4,9,15])
result=arr[(arr>=5) & (arr<=10)]
print(result)

[ 5  7 10  9]


In [27]:
#create a array randomm 3*2matrix and find the maximum and minimum value in the array
arr=np.random.randint(1,100,(3,2))
print(arr)
print("the maximum value in the array is:", arr.max())
print("the minimum value in the array is:", arr.min())

[[39 88]
 [83 46]
 [96 91]]
the maximum value in the array is: 96
the minimum value in the array is: 39


In [28]:
#delete the second column and insert a new column
sample_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Delete the second column (index 1)
sample_array = np.delete(sample_array, 1, axis=1)
# Insert a new column (e.g., all zeros) at the second position (index 1)
new_column = np.zeros((3, 1))
sample_array = np.insert(sample_array, 1, new_column, axis=1)
print("Array after deleting the second column and inserting a new column:\n", sample_array)

Array after deleting the second column and inserting a new column:
 [[1 0 0 0 3]
 [4 0 0 0 6]
 [7 0 0 0 9]]
